version: "3.8"
services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=logistics
    volumes:
        - ./scripts:/docker-entrypoint-initdb.d
  populate:
      image: logistics-datawarehouse
      links:
        - db
